# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 30221b89b8236d97f407dee8f6d09aa5bc5cf1db120be9b8efea253eb2ffcc820366bc86046296565f5c0de2beb8c327c88ecbeaf9ee50e233fe5085548c50a7

test:
  secret_key_base: 8d31bde5cf447c2858e2d89652d52ad99ff87152d9cd651329d0aafc257e0ecd79af7a373ede353eb965020cb5f7b3fd2ce69a994b9e62aeec3db65e32ca9f9d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
